Feature: Skip iterations from start.
postmanlabs/newman pull request #2664
Opened 2021-03-15 13:11 UTC by adityaofficial10

Fixes #2168 

**What does this PR do?**
This PR is in response to the feature request received under the above mentioned issue.
Functionality to skip iterations in case of csv files has been added.

**What changes have been made?**
- An option --skip-iteration has been added.
- User can skip some specified no. of iterations from the start.
- There is a lower bound and an upper bound on the no. of iterations skipped.

2021-03-15 20:43 UTC, shamasis requested changes
This is a great idea. ❤️❤️

I have left change recommendation from the code. But more than that I'm not quite sure this is the right name for the solution.

Skip iterations as a term does not match the behaviour of the code. What am I skipping? Where am I skipping from? How many does it skip? All resulting in need to cross refer documentation before usage.

Consider taking input for iteration ignoring from start point reflecting in the parameter name itself.

- [ ] Need tests
- [ ] Need parameter name change
- [ ] Need not to use single character option
- [ ] Need documentation in README
- [ ] Need some form of CLI feedback that iteration was skipped 
- [ ] Code flow itself needs to be simpler and more organised (even for the tiny feature.)

2021-03-15 20:43 UTC, shamasis commented on bin/newman.js
> +    .option('-s,--skip-iteration <value>',
Please do not reserve a single character parameter for a tertiary feature. The single characters should be kept free for major top level features.

Also, could you check the pattern of parameters for iterations and use something along those lines for the double word parameter?

2021-03-15 20:43 UTC, shamasis commented on lib/run/index.js
> +        if (options.skipIteration) {
The code flow is weird here. This block will proceed for a negative value. 

The code path complexity for such a tiny feature is unnecessarily high. Please attempt to streamline it.

- first validate
- then arrive at the range
- engage slicing on valid range

2021-03-15 20:57 UTC, adityaofficial10 commented
@shamasis 
It will be more meaningful when I complete my patch.
This is just to get it started.
Tests are being written and will be integrated in the next commit.
Thanks for your valuable feedback.
I'll make the required changes.

2021-03-16 16:44 UTC, adityaofficial10 commented
@shamasis 
i've made the required changes.
How about this?
<img width="853" alt="Screenshot 2021-03-16 at 10 12 40 PM" src="https://user-images.githubusercontent.com/65034276/111347031-d28ac380-86a4-11eb-8f6d-490579e5842d.png">

2021-03-16 18:48 UTC, shamasis commented
At this point you should check in and reconcile these with your GSOC mentor for final approvals.

PS: I would rather communicate on public forum for open code. :-)

2021-03-16 18:49 UTC, adityaofficial10 commented
> At this point you should check in and reconcile these with your GSOC mentor for final approvals.
> 
> PS: I would rather communicate on public forum for open code. :-)

Actually you reviewed it right.
So I thought if I can ask you this?

2021-04-07 10:41 UTC, adityaofficial10 commented
@coditva @codenirvana 
I've made the required changes as suggested by @shamasis .
Kindly check if it looks fine now..

2021-04-19 09:27 UTC, coditva requested changes
@adityaofficial10 Added review comments inline.

One thought, however:
We're only thinking about one use-case where users want to skip iterations at the beginning. Can we make this more generic by allowing the users to pass a range?

Thoughts? @codenirvana

2021-04-19 09:27 UTC, coditva commented on bin/newman.js
> +    .option('--ignore-iteration <n>',
Not sure if `ignore-iteration` is the correct option name. It feels like this should ignore the given iteration number. ​😅

2021-04-19 09:27 UTC, coditva commented on lib/run/index.js
> +        iterationDataLength;
We can limit the scope of these variables to function on line 102.

2021-04-19 09:27 UTC, coditva commented on lib/run/index.js
> +        }
This block seems to be adding complexity even if `options.ignoreIteration` is not set. Let's prevent this.

2021-04-19 09:27 UTC, coditva commented on test/cli/run-options.test.js
> +    });
This test seems to be checking that the run was successful. But it does not check if the option is working correctly.

2021-04-19 09:27 UTC, coditva commented on test/library/run-options.test.js
> +            collectionRunPath = path.join(__dirname, '..', '..', 'out', 'iteration-count-test.json');
You can simplify this:
```suggestion
            collectionRunPath = path.join(__dirname, '../../out/iteration-count-test.json');
```

2021-04-19 09:27 UTC, coditva commented on test/library/run-options.test.js
> +            collectionRunPath = path.join(__dirname, '..', '..', 'out', 'iteration-count-test.json');
We can limit the scope of these variables to the `it` block.

2021-04-19 09:27 UTC, coditva commented on test/unit/options.test.js
> +    });
We should also check cases where ignoreIteration has invalid values like `-1`, `> length of iteration data`, `Infinity`, etc.

2021-04-19 09:30 UTC, adityaofficial10 commented
@coditva 
Thanks for your valuable feedback.
I'll make the changes shortly..
As for the suggestion,  I was looking forward to it and if permitted, I can upgrade this...

2022-01-22 10:56 UTC, shamasis commented
https://github.com/postmanlabs/newman/pull/2652

Control which range of iteration. There seems to be two more PRs with same agenda.

- https://github.com/postmanlabs/newman/pull/2652
- https://github.com/postmanlabs/newman/pull/2664/files
- https://github.com/postmanlabs/newman/pull/2896

All the above seems to be risky to implement even when it does what it is supposed to. These should be done at runtime level. Instead of manipulating data file, runtime itself should start and end on specific iterations. It would also help it make portable across CLI and App

2022-01-22 10:56 UTC, closed without merging