Update to Warn User for invalid Folder #2791
postmanlabs/newman pull request #2843
Opened 2021-09-19 20:24 UTC by pulkit-30

Fixes #2791
Issue ' Warning or Error if `--folder` specified is invalid.'

What changes have been made?
When the user provides the wrong folder, it will warn the user, Folder (`--folder name`) not found, in the console.

Why is this change necessary?
When a user accidentally provides the wrong folder Name, then Newman doesn't show any error or warning in the console. 
To provide a better user experience this feature must be included.
I work on that issue and solved that issue.
Now, if the user passes a wrong folder, then it shows a warning, ' Folder (`--folder name`) not found ' in the console.

when the user provides two or more the wrong folder
<img width="1680" alt="3" src="https://user-images.githubusercontent.com/76155456/133941466-b6c174f8-3609-4faf-ab98-ecb722e80037.png">

when user provide one valid and one invalid folder
<img width="1680" alt="2" src="https://user-images.githubusercontent.com/76155456/133941483-0181b3d9-d767-489b-8c43-a754d1a640d3.png">

when the user provides an invalid folder only
<img width="1680" alt="1" src="https://user-images.githubusercontent.com/76155456/133941489-7705cf95-79b5-4159-b658-e09b9298fe10.png">

What side effects does this change have?
This issue doesn't have any side effects. It passes all the test cases.

2021-09-25 21:58 UTC, pulkit-30 commented
Please provide me appropriate feedback/review so that I can continue working on this.

2021-10-09 10:03 UTC, pulkit-30 commented
hey @shamasis ,
Can you provide me appropriate feedback/review so that I can continue working on this.

2021-10-17 08:41 UTC, pulkit-30 commented
Hey @coditva,
I have fixed the problem with the folder nested inside another folder. kindly review the changes and provide me appropriate feedback so that I can continue working on this.

Your idea to stop the run with an error message cannot be implemented, it doesn't pass the test cases.

2021-11-20 17:02 UTC, pulkit-30 commented
Hey @coditva @shamasis  , Please review this PR and provide me with appropriate feedback so that I can continue working on this.

2021-11-21 18:18 UTC, shamasis requested changes
Too many tiny changes for a simple feature like this.

2021-11-21 18:18 UTC, shamasis commented on lib/run/index.js
> +        let RequiredFolder = [];
@coditva @pulkit-30 is this a pattern to have variables (not constants) start with capital case for Newman?

2021-11-21 18:18 UTC, shamasis commented on lib/run/index.js
> +        function checkItems (item) {
Is this okay to acculturate all folders at the start of the run always? What will happen memory for collections with hundreds of folders?

2021-11-21 18:18 UTC, shamasis commented on lib/run/index.js
> +            item.members.forEach((Element) => {
Seems like a code styling issue with capitalisation of variables.

2021-11-21 18:18 UTC, shamasis commented on lib/run/index.js
> +                console.warn('Folder ', options.folder, ' is not found');
Since we are adding on to the errors now for general Newman run (not CLI reporter), the visual formatting / UX of the same comes into question.

2021-11-21 18:18 UTC, shamasis commented on lib/run/index.js
> +                    if (!RequiredFolder.includes(e)) {
Why are we doing n^2 loop in loop complexity here when we could simply have used a hash?

2022-07-29 16:26 UTC, pulkit-30 commented
Thanks, @shamasis for your reviews,
I will address review comments in a couple of days, 
I'm extremely sorry for my late response 😞

2022-10-21 10:05 UTC, dvanderent commented
Great if you could finish this; I found out, only after a couple of months, my pipeline test was false-positive...

2023-06-01 05:32 UTC, closed without merging